### ISSUE TITLE
关于您这个wasm产生的问题？

### ISSUE THREAD

**Issue by lecer** [doodlewind/learn-cs#5]
我想了解下这个wasm是怎么产出的，我按照您指出的 <使用WebAssembly+FFmpeg实现前端视频转码>文章生成出wasm及ffmpeg之后，发现并不能运行。一直提示

worker.js:1 Uncaught (in promise) abort({}) at Error
    at jsStackTrace (http://localhost:63342/compile/video2/ffmpeg.js:1:13475)
    at stackTrace (http://localhost:63342/compile/video2/ffmpeg.js:1:13646)
    at abort (http://localhost:63342/compile/video2/ffmpeg.js:1:225605)
    at http://localhost:63342/compile/video2/ffmpeg.js:1:26134

**Comment by lecer** [comment]
当然，您的demo没问题_

**Comment by doodlewind** [comment]
@lecer 我也是按照这篇文章的指南做的构建。如果自己搭建的 ffmpeg 编译步骤有问题，不妨用下面这个仓库（或它的 upstream 仓库）来构建 wasm 文件，这里的配置在 Linux 下应当是没有问题的，但 macOS 下可能有坑：
https://github.com/doodlewind/videoconverter.js

**Comment by lecer** [comment]
谢谢，确实是你说的这个库可以。而原文中的官方https://github.com/bgrins/videoconverter.js反而不可以。

**Comment by lecer** [comment]
我想向你了解下
原文用的是
arguments: ['-i', '/input/' + files[0].name, '-b:v', '64k', '-bufsize', '64k', '-vf', 'showinfo', '-strict', '-2', 'out.mp4'],
而在你的Demo里用的是
 arguments: ['-i', '/input/' + files[0].name, '-strict', '-2','-b:v', '2M','out.mp4'],

你是在哪儿查的，把-bufsize等删掉，只留了码率信息
而我用
argments:['-i', '/input/'+ files[0].name +' -map', '0', '-c:a', 'copy', '-c:s', 'copy', '-c:v', 'libx264', 'out.mp4']
这个不可以，我想实现是H.265编码向H.264转换

**Comment by doodlewind** [comment]
@lecer 猜测你这里出问题的应该是 `libx264` 这个参数。默认下由于有 GPL 污染之类的问题，ffmpeg 不会编译这个解码器。如果需要加上它，可以参考 videoconverter.js 的文档，在编译时把它加上（我没有尝试过 😅 如果成功希望可以分享一些经验哈）
